// src/lib/components/BlurText.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  interface Props {
    text?: string
    delay?: number
    className?: string
    animateBy?: 'words' | 'letters'
    direction?: 'top' | 'bottom'
    threshold?: number
    rootMargin?: string
    onAnimationComplete?: () => void
  }

  let {
    text = '',
    delay = 200,
    className = '',
    animateBy = 'words',
    direction = 'top',
    threshold = 0.1,
    rootMargin = '0px',
    onAnimationComplete,
  }: Props = $props()

  let elements = $derived(animateBy === 'words' ? text.split(' ') : text.split(''))
  let inView = $state(false)
  let ref: HTMLParagraphElement

  onMount(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          inView = true
          observer.unobserve(ref)
          if (onAnimationComplete) {
            const maxDelay = (elements.length - 1) * delay + 700
            setTimeout(onAnimationComplete, maxDelay)
          }
        }
      },
      { threshold, rootMargin },
    )
    observer.observe(ref)
    return () => observer.disconnect()
  })
</script>

<p bind:this={ref} class="blur-text {className} flex flex-wrap">
  {#each elements as element, i}
    <span
      class="inline-block will-change-[transform,filter,opacity]"
      style="
        transition-property: filter, opacity, transform;
        transition-duration: 700ms;
        transition-timing-function: cubic-bezier(0.22, 1, 0.36, 1);
        transition-delay: {i * delay}ms;
        filter: {inView ? 'blur(0px)' : 'blur(10px)'};
        opacity: {inView ? 1 : 0};
        transform: {inView
        ? 'translate3d(0,0,0)'
        : `translate3d(0,${direction === 'top' ? '-50px' : '50px'},0)`};
      "
    >{element === ' ' ? '\u00A0' : element}{animateBy === 'words' &&
      i < elements.length - 1
      ? '\u00A0'
      : ''}</span>
  {/each}
</p>

// src/components/bits/text-animations/BlurText/BlurText.tsx
'use client'

import { type SpringValue, animated, useSprings } from '@react-spring/web'
import { useEffect, useRef, useState } from 'react'

interface BlurTextProps {
  text?: string
  delay?: number
  className?: string
  animateBy?: 'words' | 'letters'
  direction?: 'top' | 'bottom'
  threshold?: number
  rootMargin?: string
  animationFrom?: Record<string, any>
  animationTo?: Record<string, any>[]
  easing?: (t: number) => number | string
  onAnimationComplete?: () => void
}

const BlurText: React.FC<BlurTextProps> = ({
  text = '',
  delay = 200,
  className = '',
  animateBy = 'words',
  direction = 'top',
  threshold = 0.1,
  rootMargin = '0px',
  animationFrom,
  animationTo,
  easing = 'easeOutCubic',
  onAnimationComplete,
}) => {
  const elements = animateBy === 'words' ? text.split(' ') : text.split('')
  const [inView, setInView] = useState(false)
  const ref = useRef<HTMLParagraphElement>(null)
  const animatedCount = useRef(0)

  // Default animations based on direction
  const defaultFrom: Record<string, any> =
    direction === 'top'
      ? {
          filter: 'blur(10px)',
          opacity: 0,
          transform: 'translate3d(0,-50px,0)',
        }
      : {
          filter: 'blur(10px)',
          opacity: 0,
          transform: 'translate3d(0,50px,0)',
        }

  const defaultTo: Record<string, any>[] = [
    {
      filter: 'blur(5px)',
      opacity: 0.5,
      transform:
        direction === 'top' ? 'translate3d(0,5px,0)' : 'translate3d(0,-5px,0)',
    },
    { filter: 'blur(0px)', opacity: 1, transform: 'translate3d(0,0,0)' },
  ]

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setInView(true)
          if (ref.current) {
            observer.unobserve(ref.current)
          }
        }
      },
      { threshold, rootMargin },
    )

    if (ref.current) {
      observer.observe(ref.current)
    }

    return () => observer.disconnect()
  }, [threshold, rootMargin])

  const springs = useSprings(
    elements.length,
    elements.map((_, i) => ({
      from: animationFrom || defaultFrom,
      to: inView
        ? async (
            next: (arg: Record<string, SpringValue<any>>) => Promise<void>,
          ) => {
            for (const step of animationTo || defaultTo) {
              await next(step)
            }
            animatedCount.current += 1
            if (
              animatedCount.current === elements.length &&
              onAnimationComplete
            ) {
              onAnimationComplete()
            }
          }
        : animationFrom || defaultFrom,
      delay: i * delay,
      config: { easing: easing as any },
    })),
  )

  return (
    <p ref={ref} className={`blur-text ${className} flex flex-wrap`}>
      {springs.map((props, index) => (
        // @ts-ignore
        <animated.span
          key={JSON.stringify(index)}
          style={props}
          className="inline-block transition-transform will-change-[transform,filter,opacity]"
        >
          {elements[index] === ' ' ? '\u00A0' : elements[index]}
          {animateBy === 'words' && index < elements.length - 1 && '\u00A0'}
        </animated.span>
      ))}
    </p>
  )
}

export default BlurText
