// src/components/bits/text-animations/RotatingText/RotatingText.tsx
/*
	jsrepo 1.41.3
	Installed from https://reactbits.dev/ts/tailwind/
	3-4-2025
*/
'use client'

import { AnimatePresence, type Transition, motion } from 'framer-motion'
// biome-ignore lint/style/useImportType: <explanation>
import React, {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useState,
} from 'react'

function cn(...classes: (string | undefined | null | boolean)[]): string {
  return classes.filter(Boolean).join(' ')
}

export interface RotatingTextRef {
  next: () => void
  previous: () => void
  jumpTo: (index: number) => void
  reset: () => void
}

export interface RotatingTextProps
  extends Omit<
    React.ComponentPropsWithoutRef<typeof motion.span>,
    'children' | 'transition' | 'initial' | 'animate' | 'exit'
  > {
  texts: string[]
  transition?: Transition
  initial?: any
  animate?: any
  exit?: any
  animatePresenceMode?: 'sync' | 'wait'
  animatePresenceInitial?: boolean
  rotationInterval?: number
  staggerDuration?: number
  staggerFrom?: 'first' | 'last' | 'center' | 'random' | number
  loop?: boolean
  auto?: boolean
  splitBy?: string
  onNext?: (index: number) => void
  mainClassName?: string
  splitLevelClassName?: string
  elementLevelClassName?: string
}

const RotatingText = forwardRef<RotatingTextRef, RotatingTextProps>(
  (
    {
      texts,
      transition = { type: 'spring', damping: 25, stiffness: 300 },
      initial = { y: '100%', opacity: 0 },
      animate = { y: 0, opacity: 1 },
      exit = { y: '-120%', opacity: 0 },
      animatePresenceMode = 'wait',
      animatePresenceInitial = false,
      rotationInterval = 2000,
      staggerDuration = 0,
      staggerFrom = 'first',
      loop = true,
      auto = true,
      splitBy = 'characters',
      onNext,
      mainClassName,
      splitLevelClassName,
      elementLevelClassName,
      ...rest
    },
    ref,
  ) => {
    const [currentTextIndex, setCurrentTextIndex] = useState<number>(0)

    const splitIntoCharacters = (text: string): string[] => {
      if (typeof Intl !== 'undefined' && Intl.Segmenter) {
        const segmenter = new Intl.Segmenter('en', { granularity: 'grapheme' })
        return Array.from(segmenter.segment(text), segment => segment.segment)
      }
      return Array.from(text)
    }

    const elements = useMemo(() => {
      const currentText: string = texts[currentTextIndex]
      if (splitBy === 'characters') {
        const words = currentText.split(' ')
        return words.map((word, i) => ({
          characters: splitIntoCharacters(word),
          needsSpace: i !== words.length - 1,
        }))
      }
      if (splitBy === 'words') {
        return currentText.split(' ').map((word, i, arr) => ({
          characters: [word],
          needsSpace: i !== arr.length - 1,
        }))
      }
      if (splitBy === 'lines') {
        return currentText.split('\n').map((line, i, arr) => ({
          characters: [line],
          needsSpace: i !== arr.length - 1,
        }))
      }

      return currentText.split(splitBy).map((part, i, arr) => ({
        characters: [part],
        needsSpace: i !== arr.length - 1,
      }))
    }, [texts, currentTextIndex, splitBy])

    const getStaggerDelay = useCallback(
      (index: number, totalChars: number): number => {
        const total = totalChars
        if (staggerFrom === 'first') {
          return index * staggerDuration
        }
        if (staggerFrom === 'last') {
          return (total - 1 - index) * staggerDuration
        }
        if (staggerFrom === 'center') {
          const center = Math.floor(total / 2)
          return Math.abs(center - index) * staggerDuration
        }
        if (staggerFrom === 'random') {
          const randomIndex = Math.floor(Math.random() * total)
          return Math.abs(randomIndex - index) * staggerDuration
        }
        return Math.abs((staggerFrom as number) - index) * staggerDuration
      },
      [staggerFrom, staggerDuration],
    )

    const handleIndexChange = useCallback(
      (newIndex: number) => {
        setCurrentTextIndex(newIndex)
        if (onNext) {
          onNext(newIndex)
        }
      },
      [onNext],
    )

    const next = useCallback(() => {
      const nextIndex =
        currentTextIndex === texts.length - 1
          ? loop
            ? 0
            : currentTextIndex
          : currentTextIndex + 1
      if (nextIndex !== currentTextIndex) {
        handleIndexChange(nextIndex)
      }
    }, [currentTextIndex, texts.length, loop, handleIndexChange])

    const previous = useCallback(() => {
      const prevIndex =
        currentTextIndex === 0
          ? loop
            ? texts.length - 1
            : currentTextIndex
          : currentTextIndex - 1
      if (prevIndex !== currentTextIndex) {
        handleIndexChange(prevIndex)
      }
    }, [currentTextIndex, texts.length, loop, handleIndexChange])

    const jumpTo = useCallback(
      (index: number) => {
        const validIndex = Math.max(0, Math.min(index, texts.length - 1))
        if (validIndex !== currentTextIndex) {
          handleIndexChange(validIndex)
        }
      },
      [texts.length, currentTextIndex, handleIndexChange],
    )

    const reset = useCallback(() => {
      if (currentTextIndex !== 0) {
        handleIndexChange(0)
      }
    }, [currentTextIndex, handleIndexChange])

    useImperativeHandle(
      ref,
      () => ({
        next,
        previous,
        jumpTo,
        reset,
      }),
      [next, previous, jumpTo, reset],
    )

    useEffect(() => {
      if (!auto) {
        return
      }
      const intervalId = setInterval(next, rotationInterval)
      return () => clearInterval(intervalId)
    }, [next, rotationInterval, auto])

    return (
      <motion.span
        className={cn(
          'flex flex-wrap whitespace-pre-wrap relative',
          mainClassName,
        )}
        {...rest}
        layout
        transition={transition}
      >
        <span className="sr-only">{texts[currentTextIndex]}</span>
        <AnimatePresence
          mode={animatePresenceMode}
          initial={animatePresenceInitial}
        >
          <motion.div
            key={currentTextIndex}
            className={cn(
              splitBy === 'lines'
                ? 'flex flex-col w-full'
                : 'flex flex-wrap whitespace-pre-wrap relative',
            )}
            layout
            aria-hidden="true"
          >
            {elements.map((wordObj, wordIndex, array) => {
              const previousCharsCount = array
                .slice(0, wordIndex)
                .reduce((sum, word) => sum + word.characters.length, 0)
              return (
                <span
                  key={wordIndex}
                  className={cn('inline-flex', splitLevelClassName)}
                >
                  {wordObj.characters.map((char, charIndex) => (
                    <motion.span
                      key={charIndex}
                      initial={initial}
                      animate={animate}
                      exit={exit}
                      transition={{
                        ...transition,
                        delay: getStaggerDelay(
                          previousCharsCount + charIndex,
                          array.reduce(
                            (sum, word) => sum + word.characters.length,
                            0,
                          ),
                        ),
                      }}
                      className={cn('inline-block', elementLevelClassName)}
                    >
                      {char}
                    </motion.span>
                  ))}
                  {wordObj.needsSpace && (
                    <span className="whitespace-pre"> </span>
                  )}
                </span>
              )
            })}
          </motion.div>
        </AnimatePresence>
      </motion.span>
    )
  },
)

RotatingText.displayName = 'RotatingText'
export default RotatingText

// src/lib/components/RotatingText.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  interface Props {
    texts: string[]
    mainClassName?: string
    splitLevelClassName?: string
    elementLevelClassName?: string
    rotationInterval?: number
    staggerDuration?: number
    staggerFrom?: 'first' | 'last' | 'center' | 'random' | number
    loop?: boolean
    auto?: boolean
  }

  let {
    texts,
    mainClassName = '',
    splitLevelClassName = '',
    elementLevelClassName = '',
    rotationInterval = 2000,
    staggerDuration = 0,
    staggerFrom = 'first' as 'first' | 'last' | 'center' | 'random' | number,
    loop = true,
    auto = true,
  }: Props = $props()

  type CharItem = { char: string; isSpace: boolean; delay: number }

  let currentIndex = $state(0)
  let phase = $state<'entering' | 'exiting' | 'idle'>('entering')
  let busy = false

  function splitChars(text: string): string[] {
    if (typeof Intl !== 'undefined' && Intl.Segmenter) {
      const seg = new Intl.Segmenter('en', { granularity: 'grapheme' })
      return Array.from(seg.segment(text), s => s.segment)
    }
    return Array.from(text)
  }

  function buildChars(index: number): CharItem[] {
    const words = texts[index].split(' ')
    const items: CharItem[] = []

    words.forEach((word, wi) => {
      splitChars(word).forEach(char => items.push({ char, isSpace: false, delay: 0 }))
      if (wi < words.length - 1) items.push({ char: ' ', isSpace: true, delay: 0 })
    })

    const nonSpace = items.filter(c => !c.isSpace)
    const total = nonSpace.length
    const d = staggerDuration * 1000 // seconds → milliseconds
    let nonSpaceIdx = 0

    items.forEach(c => {
      if (c.isSpace) return
      const i = nonSpaceIdx++
      if (staggerFrom === 'first') c.delay = i * d
      else if (staggerFrom === 'last') c.delay = (total - 1 - i) * d
      else if (staggerFrom === 'center')
        c.delay = Math.abs(Math.floor(total / 2) - i) * d
      else if (staggerFrom === 'random')
        c.delay = Math.abs(Math.floor(Math.random() * total) - i) * d
      else c.delay = Math.abs((staggerFrom as number) - i) * d
    })

    return items
  }

  function maxDelay(charItems: CharItem[]): number {
    const delays = charItems.filter(c => !c.isSpace).map(c => c.delay)
    return delays.length > 0 ? Math.max(...delays) : 0
  }

  let chars = $derived(buildChars(currentIndex))

  const EXIT_DURATION = 300
  const ENTER_DURATION = 350

  async function rotate() {
    if (busy) return
    busy = true

    const nextIndex = loop
      ? (currentIndex + 1) % texts.length
      : Math.min(currentIndex + 1, texts.length - 1)

    if (nextIndex === currentIndex) {
      busy = false
      return
    }

    const exitMax = maxDelay(chars)
    phase = 'exiting'
    await new Promise<void>(r => setTimeout(r, exitMax + EXIT_DURATION + 20))

    // Both state updates are batched by Svelte into a single render:
    // new chars (from new currentIndex) get the entering class from the start.
    currentIndex = nextIndex
    phase = 'entering'

    const enterMax = maxDelay(chars)
    await new Promise<void>(r => setTimeout(r, enterMax + ENTER_DURATION + 20))

    phase = 'idle'
    busy = false
  }

  onMount(() => {
    if (!auto) return
    const id = setInterval(rotate, rotationInterval)
    return () => clearInterval(id)
  })
</script>

<span class="flex flex-wrap whitespace-pre-wrap relative {mainClassName}">
  <span class="sr-only">{texts[currentIndex]}</span>
  <span class="flex flex-wrap whitespace-pre-wrap relative" aria-hidden="true">
    {#each chars as item}
      {#if item.isSpace}
        <span class="whitespace-pre"> </span>
      {:else}
        <span class="inline-flex {splitLevelClassName}">
          <span
            class="inline-block {elementLevelClassName}"
            class:char-entering={phase === 'entering'}
            class:char-exiting={phase === 'exiting'}
            style="animation-delay: {item.delay}ms"
          >{item.char}</span>
        </span>
      {/if}
    {/each}
  </span>
</span>

<style>
  .char-entering {
    animation: charEnter 350ms cubic-bezier(0.22, 1, 0.36, 1) both;
  }

  .char-exiting {
    animation: charExit 300ms cubic-bezier(0.22, 1, 0.36, 1) both;
  }

  @keyframes charEnter {
    from {
      transform: translateY(100%);
    }
    to {
      transform: translateY(0);
    }
  }

  @keyframes charExit {
    from {
      transform: translateY(0);
    }
    to {
      transform: translateY(-120%);
    }
  }
</style>
